### ISSUE TITLE
Multiple (different) renames possible in 1 pass?

### ISSUE THREAD

**Issue by luckman212** [ismaelgv/rnr#36]
Thank you for this amazing tool.

I am wondering if it's possible to achieve the following in a single pass of rnr:

```
.
├── dir1/
│   ├── file:with_a_*
│   └── file2_also_has<a_**-3
└── dir2/
    └── some!<other_file": ok?
```
I want to change `[*<"?!]` chars to underscores `_` _and_ change colon `:` to ` - ` (hyphen surrounded by space)

Final result should be:

```
.
├── dir1/
│   ├── file - with_a__
│   └── file2_also_has_a___-3
└── dir2/
    └── some__other_file_ -  ok?
```

Is it possible?

**Comment by ismaelgv** [comment]
@luckman212 I am glad that `rnr` is useful to you. Thanks for the kind words.

About your question, I think the easiest way to solve that problem is to run just two different commands.

You may try to create an elaborated regexp with capture groups since they are supported. However, I believe that it is not worth it for this case. You can check the examples for more info about the capture groups.

**Comment by luckman212** [comment]
Ok, that's what I thought. Just wanted to be sure. I ended up doing it in 2 separate passes and it worked fine.
